name: Generate Resume
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Build Styled HTML
        run: |
          mkdir -p dist
          pandoc resume.md -o dist/index.html \
          --standalone \
          --embed-resources \
          --css=style.css \
          --metadata title="Muhammad Mustaqim"
      - name: Build PDF
        run: |
          pandoc resume.md -o dist/resume.pdf \
          --pdf-engine=xelatex \
          --metadata title="Muhammad Mustaqim"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages  # It is better to keep your built HTML separate from your Markdown