name: Generate Resume
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Build Styled HTML
        run: |
          pandoc resume.md -o index.html \
          --standalone \
          --self-contained \
          --css=style.css \
          --metadata title="Resume - Mustaqim"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages